[versions]
jvm = "2.0.0"
paper = "1.21-R0.1-SNAPSHOT"
kspigot = "1.20.4"
run-paper = "2.0.1"
plugin-yml = "0.6.0"
kotlinx-serialization = "1.6.3"
shadow = "8.1.1"

[libraries]
paper-api = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
kspigot = { group = "net.axay", name = "kspigot", version.ref = "kspigot" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jvm" }
runpaper = { id = "xyz.jpenilla.run-paper", version.ref = "run-paper" }
pluginyml = { id = "net.minecrell.plugin-yml.paper", version.ref = "plugin-yml" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "jvm" }
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }

[bundles]
paper = ["paper-api", "kspigot"]
serialization = ["kotlinx-serialization-json"]